/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SyntheticDataImport } from './routes/synthetic-data'
import { Route as BiasDetectionImport } from './routes/bias-detection'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SyntheticDataRoute = SyntheticDataImport.update({
  path: '/synthetic-data',
  getParentRoute: () => rootRoute,
} as any)

const BiasDetectionRoute = BiasDetectionImport.update({
  path: '/bias-detection',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/bias-detection': {
      id: '/bias-detection'
      path: '/bias-detection'
      fullPath: '/bias-detection'
      preLoaderRoute: typeof BiasDetectionImport
      parentRoute: typeof rootRoute
    }
    '/synthetic-data': {
      id: '/synthetic-data'
      path: '/synthetic-data'
      fullPath: '/synthetic-data'
      preLoaderRoute: typeof SyntheticDataImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BiasDetectionRoute,
  SyntheticDataRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bias-detection",
        "/synthetic-data"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/bias-detection": {
      "filePath": "bias-detection.tsx"
    },
    "/synthetic-data": {
      "filePath": "synthetic-data.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
