name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and deploy Vue.js front-end application
        run: |
          cd frontend
          npm install
          npm run build
          aws s3 sync dist/ s3://${{ secrets.YOUR_S3_BUCKET_NAME }}

      - name: Configure S3 CORS
        run: |
          aws s3api put-bucket-cors --bucket ${{ secrets.YOUR_S3_BUCKET_NAME }} --cors-configuration '{
            "CORSRules": [
              {
                "AllowedOrigins": ["https://algorithmaudit.eu", "http://localhost"],
                "AllowedMethods": ["GET"],
                "AllowedHeaders": ["*"],
                "MaxAgeSeconds": 3000
              }
            ]
          }'
